#:schema node_modules/wrangler/config-schema.json
name = "status"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "UPTIMEFLARE_D1"
database_name = "uptimeflare_d1"
database_id = "a0fbcdd3-06f0-4548-bf1c-fa707a33f0b5"
